#!/usr/bin/env bash

set -euo pipefail

# デフォルト値
DEFAULT_ALLOWED_SIGNERS="~/git.allowed_signers"

# 色の定義
readonly COLOR_RESET='\033[0m'
readonly COLOR_BOLD='\033[1m'
readonly COLOR_GREEN='\033[0;32m'
readonly COLOR_YELLOW='\033[0;33m'
readonly COLOR_CYAN='\033[0;36m'

# メッセージ表示
print_header() {
    echo -e "${COLOR_BOLD}${COLOR_CYAN}$1${COLOR_RESET}"
}

print_success() {
    echo -e "${COLOR_GREEN}✓${COLOR_RESET} $1"
}

print_warning() {
    echo -e "${COLOR_YELLOW}⚠${COLOR_RESET} $1"
}

# 設定ファイルのパス
CONFIG_DIR="${HOME}/.config/git"
CONFIG_FILE="${CONFIG_DIR}/config"

# ディレクトリの作成
if [[ ! -d "${CONFIG_DIR}" ]]; then
    echo "ディレクトリを作成します: ${CONFIG_DIR}"
    mkdir -p "${CONFIG_DIR}"
fi

# ヘッダー表示
echo ""
print_header "=== Git 設定ファイル生成ツール ==="
echo ""

# 既存ファイルの確認
if [[ -f "${CONFIG_FILE}" ]]; then
    print_warning "既存の設定ファイルが見つかりました: ${CONFIG_FILE}"
    echo "現在の内容:"
    echo "----------------------------------------"
    cat "${CONFIG_FILE}"
    echo "----------------------------------------"
    echo ""
    read -p "上書きしますか? (y/N): " -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "キャンセルしました。"
        exit 0
    fi

    # バックアップ作成
    BACKUP_FILE="${CONFIG_FILE}.bak.$(date +%Y%m%d_%H%M%S)"
    echo "バックアップを作成します: ${BACKUP_FILE}"
    cp "${CONFIG_FILE}" "${BACKUP_FILE}"
    echo ""
fi

# 組織エイリアスの収集
print_header "組織設定"
echo "組織エイリアスを入力してください。"
echo "エイリアスから以下が自動生成されます:"
echo "  - gitdir: ~/projects/github.com/{エイリアス}/"
echo "  - path: ~/{エイリアス}.git.inc"
echo ""

ORG_ALIASES=()

while true; do
    if [[ ${#ORG_ALIASES[@]} -eq 0 ]]; then
        read -p "組織エイリアス (例: classi): " org_alias
    else
        read -p "追加の組織エイリアス (空白でスキップ): " org_alias
    fi

    if [[ -n "${org_alias}" ]]; then
        ORG_ALIASES+=("${org_alias}")
        print_success "追加: ~/projects/github.com/${org_alias}/ → ~/${org_alias}.git.inc"
    elif [[ ${#ORG_ALIASES[@]} -eq 0 ]]; then
        echo "最低1つの組織エイリアスが必要です。"
        continue
    else
        break
    fi
done

echo ""

# allowed signers ファイルの設定
print_header "GPG SSH署名設定"
echo "allowed signers ファイルのパスを入力してください。"
read -p "パス (デフォルト: ${DEFAULT_ALLOWED_SIGNERS}): " allowed_signers_input

if [[ -z "${allowed_signers_input}" ]]; then
    ALLOWED_SIGNERS="${DEFAULT_ALLOWED_SIGNERS}"
else
    ALLOWED_SIGNERS="${allowed_signers_input}"
fi

echo ""

# 設定内容の確認
print_header "設定内容の確認"
echo "以下の内容でファイルを生成します:"
echo ""
echo "[include]"
echo "  path = ~/.config/git/global.config"
echo ""
echo "[gpg \"ssh\"]"
echo "  allowedSignersFile = ${ALLOWED_SIGNERS}"
echo ""
for org_alias in "${ORG_ALIASES[@]}"; do
    echo "[includeIf \"gitdir:~/projects/github.com/${org_alias}/\"]"
    echo "  path = ~/${org_alias}.git.inc"
    echo ""
done

read -p "この内容で生成しますか? (Y/n): " -r
echo
if [[ $REPLY =~ ^[Nn]$ ]]; then
    echo "キャンセルしました。"
    exit 0
fi

# 設定ファイルの生成
print_header "ファイル生成中..."

cat > "${CONFIG_FILE}" <<EOF
# Generated by setup-config.sh on $(date +%Y-%m-%d\ %H:%M:%S)
#
# このファイルは自動生成されました。手動で編集する場合は注意してください。

[include]
	path = ~/.config/git/global.config
[gpg "ssh"]
	allowedSignersFile = ${ALLOWED_SIGNERS}
EOF

# 組織設定を追加
for org_alias in "${ORG_ALIASES[@]}"; do
    cat >> "${CONFIG_FILE}" <<EOF
[includeIf "gitdir:~/projects/github.com/${org_alias}/"]
	path = ~/${org_alias}.git.inc
EOF
done

echo ""
print_success "設定ファイルを作成しました: ${CONFIG_FILE}"
echo ""
echo "生成された内容:"
echo "----------------------------------------"
cat "${CONFIG_FILE}"
echo "----------------------------------------"
echo ""
print_header "次のステップ"
echo "1. ~/.config/git/global.config ファイルが存在することを確認してください"
for org_alias in "${ORG_ALIASES[@]}"; do
    echo "2. 組織の設定ファイル (~/${org_alias}.git.inc) を作成してください"
done
echo "3. allowed signers ファイル (${ALLOWED_SIGNERS}) を設定してください (GPG SSH署名を使用する場合)"
echo ""
print_success "完了しました！"
