#!/usr/bin/env bash

if command -v fisher &> /dev/null
  curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source && fisher install jorgebucaran/fisher
  fisher install decors/fish-ghq jethrokuan/fzf
else
  echo 'fisher already installed.'
end

if command -v omf &> /dev/null
  curl https://raw.githubusercontent.com/oh-my-fish/oh-my-fish/master/bin/install | fish
else
  echo 'oh-my-fish already installed.'
end

if not omf list | grep -q bobthefish
  omf install bobthefish
else
  echo 'bob-the-fish theme already installed.'
end
