#!/usr/bin/env fish

if not functions -q fisher
  curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source && fisher install jorgebucaran/fisher
else
  echo 'fisher already installed.'
end

fisher install decors/fish-ghq jethrokuan/fzf oh-my-fish/theme-bobthefish
