[tools]
bun = "latest"
ecspresso = "latest"
ghalint = "latest"
"go:github.com/tkdn/wire-cruiser/cmd/wire-cruiser" = "latest"
node = "24"
"npm:@anthropic-ai/claude-code" = "latest"
pnpm = "latest"
terraform = "latest"

[settings]
idiomatic_version_file_enable_tools = ["ruby"]
experimental = true

[settings.node]
gpg_verify = false

[env]
